insert into boardgame (cod_boardgame, nome, cod_categoria, quantidade_pessoas, cod_fabricante, idade_recomendada, preco) values (1, 'Gloomhaven', 3, 5, 5, '14', 197.22);
insert into boardgame (cod_boardgame, nome, cod_categoria, quantidade_pessoas, cod_fabricante, idade_recomendada, preco) values (2, 'Projeto Gaia', 6, 2, 1, '14', 220.24);
insert into boardgame (cod_boardgame, nome, cod_categoria, quantidade_pessoas, cod_fabricante, idade_recomendada, preco) values (3, 'Terra Mystica', 11, 3, 2, '8', 290.55);
insert into boardgame (cod_boardgame, nome, cod_categoria, quantidade_pessoas, cod_fabricante, idade_recomendada, preco) values (4, 'Terraforming Mars', 4, 2, 3, '16', 66.08);
insert into boardgame (cod_boardgame, nome, cod_categoria, quantidade_pessoas, cod_fabricante, idade_recomendada, preco) values (5, 'Brass: Birmingham', 1, 6, 7, '10', 235.4);
insert into boardgame (cod_boardgame, nome, cod_categoria, quantidade_pessoas, cod_fabricante, idade_recomendada, preco) values (6, 'Twilight Imperium (Quarta Edição)', 8, 3, 2, '8', 92.68);
insert into boardgame (cod_boardgame, nome, cod_categoria, quantidade_pessoas, cod_fabricante, idade_recomendada, preco) values (7, 'Great Western Trail', 2, 8, 1, '12', 238.4);
insert into boardgame (cod_boardgame, nome, cod_categoria, quantidade_pessoas, cod_fabricante, idade_recomendada, preco) values (8, 'The Castles of Burgundy', 9, 8, 4, '12', 98.63);
insert into boardgame (cod_boardgame, nome, cod_categoria, quantidade_pessoas, cod_fabricante, idade_recomendada, preco) values (9, 'Clãs da Caledônia', 4, 5, 5, '18+', 289.11);
insert into boardgame (cod_boardgame, nome, cod_categoria, quantidade_pessoas, cod_fabricante, idade_recomendada, preco) values (10, 'Star Wars: Rebellion', 8, 6, 5, '18+', 255.0);
insert into boardgame (cod_boardgame, nome, cod_categoria, quantidade_pessoas, cod_fabricante, idade_recomendada, preco) values (11, '7 Wonders Duel', 7, 8, 6, '16', 145.24);
insert into boardgame (cod_boardgame, nome, cod_categoria, quantidade_pessoas, cod_fabricante, idade_recomendada, preco) values (12, 'Puerto Rico', 5, 3, 4, '10', 187.57);
insert into boardgame (cod_boardgame, nome, cod_categoria, quantidade_pessoas, cod_fabricante, idade_recomendada, preco) values (13, 'Spirit Island', 11, 5, 1, '12', 194.48);
insert into boardgame (cod_boardgame, nome, cod_categoria, quantidade_pessoas, cod_fabricante, idade_recomendada, preco) values (14, 'Lisboa', 8, 3, 4, '16', 251.94);
insert into boardgame (cod_boardgame, nome, cod_categoria, quantidade_pessoas, cod_fabricante, idade_recomendada, preco) values (15, 'Twilight Struggle', 1, 7, 6, '10', 269.0);
insert into boardgame (cod_boardgame, nome, cod_categoria, quantidade_pessoas, cod_fabricante, idade_recomendada, preco) values (16, 'Um Banquete a Odin', 11, 6, 2, '18+', 65.41);
insert into boardgame (cod_boardgame, nome, cod_categoria, quantidade_pessoas, cod_fabricante, idade_recomendada, preco) values (17, 'Five Tribes', 10, 6, 1, '8', 187.95);
insert into boardgame (cod_boardgame, nome, cod_categoria, quantidade_pessoas, cod_fabricante, idade_recomendada, preco) values (18, 'Mansions of Madness (2ª Edição)', 7, 2, 7, '18+', 206.2);
insert into boardgame (cod_boardgame, nome, cod_categoria, quantidade_pessoas, cod_fabricante, idade_recomendada, preco) values (19, 'O Senhor dos Anéis: Jornadas na Terra Média', 8, 2, 3, '14', 198.87);
insert into boardgame (cod_boardgame, nome, cod_categoria, quantidade_pessoas, cod_fabricante, idade_recomendada, preco) values (20, 'Root', 5, 8, 5, '14', 172.44);
insert into boardgame (cod_boardgame, nome, cod_categoria, quantidade_pessoas, cod_fabricante, idade_recomendada, preco) values (21, 'Maracaibo', 10, 3, 7, '18+', 102.61);
insert into boardgame (cod_boardgame, nome, cod_categoria, quantidade_pessoas, cod_fabricante, idade_recomendada, preco) values (22, 'Mage Knight Board Game', 9, 2, 1, '10', 206.95);
insert into boardgame (cod_boardgame, nome, cod_categoria, quantidade_pessoas, cod_fabricante, idade_recomendada, preco) values (23, 'Catan', 11, 2, 2, '12', 51.39);
insert into boardgame (cod_boardgame, nome, cod_categoria, quantidade_pessoas, cod_fabricante, idade_recomendada, preco) values (24, 'Concordia', 10, 4, 7, '12', 120.06);
insert into boardgame (cod_boardgame, nome, cod_categoria, quantidade_pessoas, cod_fabricante, idade_recomendada, preco) values (25, 'Power Grid', 1, 7, 1, '14', 158.01);
insert into boardgame (cod_boardgame, nome, cod_categoria, quantidade_pessoas, cod_fabricante, idade_recomendada, preco) values (26, 'Azul', 11, 5, 6, '18+', 149.72);
insert into boardgame (cod_boardgame, nome, cod_categoria, quantidade_pessoas, cod_fabricante, idade_recomendada, preco) values (27, 'Ticket to Ride', 3, 3, 1,'10', 205.78);
insert into boardgame (cod_boardgame, nome, cod_categoria, quantidade_pessoas, cod_fabricante, idade_recomendada, preco) values (28, 'Ilha dos Dinossauros', 5, 5, 3, '8', 258.05);
