insert into categoria (cod_categoria, nome) values (1, 'Abstratos');
insert into categoria (cod_categoria, nome) values (2, 'American Games');
insert into categoria (cod_categoria, nome) values (3, 'Euro Games');
insert into categoria (cod_categoria, nome) values (4, 'Duel Games');
insert into categoria (cod_categoria, nome) values (5, 'Filler Games');
insert into categoria (cod_categoria, nome) values (6, 'Family Games');
insert into categoria (cod_categoria, nome) values (7, 'Infantis');
insert into categoria (cod_categoria, nome) values (8, 'Party Games');
insert into categoria (cod_categoria, nome) values (9, 'Quebra-Cabeças');
insert into categoria (cod_categoria, nome) values (10, 'Race Games');
insert into categoria (cod_categoria, nome) values (11, 'War Games');